/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/navigation/AppHeader.vue')['default']
    AppNavigationDrawer: typeof import('./src/components/navigation/AppNavigationDrawer.vue')['default']
    CultivationAchievements: typeof import('./src/components/cultivation/CultivationAchievements.vue')['default']
    CultivationHistory: typeof import('./src/components/cultivation/CultivationHistory.vue')['default']
    CultivationRealmGuide: typeof import('./src/components/cultivation/CultivationRealmGuide.vue')['default']
    CultivationTodoList: typeof import('./src/components/cultivation/CultivationTodoList.vue')['default']
    DailyTaskList: typeof import('./src/components/DailyTaskList.vue')['default']
    FeedbackList: typeof import('./src/components/FeedbackList.vue')['default']
    GroupsManagement: typeof import('./src/components/admin/GroupsManagement.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MascotCow: typeof import('./src/components/MascotCow.vue')['default']
    MessageBoard: typeof import('./src/components/MessageBoard.vue')['default']
    MyPermissions: typeof import('./src/components/admin/MyPermissions.vue')['default']
    ProjectDialog: typeof import('./src/components/projects/ProjectDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoDialog: typeof import('./src/components/todos/TodoDialog.vue')['default']
    TodoStatistics: typeof import('./src/components/todos/TodoStatistics.vue')['default']
    UserSearch: typeof import('./src/components/admin/UserSearch.vue')['default']
    WikiCommentItem: typeof import('./src/components/wiki/WikiCommentItem.vue')['default']
    WikiComments: typeof import('./src/components/wiki/WikiComments.vue')['default']
    WikiCreateDialog: typeof import('./src/components/wiki/WikiCreateDialog.vue')['default']
    WikiEditDialog: typeof import('./src/components/wiki/WikiEditDialog.vue')['default']
    WikiFolderItem: typeof import('./src/components/WikiFolderItem.vue')['default']
    WikiHistoryDialog: typeof import('./src/components/wiki/WikiHistoryDialog.vue')['default']
    WikiMoveDialog: typeof import('./src/components/wiki/WikiMoveDialog.vue')['default']
    WikiPermissionDialog: typeof import('./src/components/wiki/WikiPermissionDialog.vue')['default']
    WikiPermissionsManagement: typeof import('./src/components/admin/WikiPermissionsManagement.vue')['default']
    WikiTagsDialog: typeof import('./src/components/wiki/WikiTagsDialog.vue')['default']
    WikiTreeItem: typeof import('./src/components/wiki/WikiTreeItem.vue')['default']
    WikiTreeItemCompact: typeof import('./src/components/wiki/WikiTreeItemCompact.vue')['default']
  }
}
