/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin/permissions': RouteRecordInfo<'/admin/permissions', '/admin/permissions', Record<never, never>, Record<never, never>>,
    '/autops': RouteRecordInfo<'/autops', '/autops', Record<never, never>, Record<never, never>>,
    '/leave_form_info/[uuid]': RouteRecordInfo<'/leave_form_info/[uuid]', '/leave_form_info/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/loading': RouteRecordInfo<'/loading', '/loading', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/notion/': RouteRecordInfo<'/notion/', '/notion', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[id]': RouteRecordInfo<'/projects/[id]', '/projects/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/pure-loading': RouteRecordInfo<'/pure-loading', '/pure-loading', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/todos': RouteRecordInfo<'/todos', '/todos', Record<never, never>, Record<never, never>>,
    '/wiki/[[id]]': RouteRecordInfo<'/wiki/[[id]]', '/wiki/:id?', { id?: ParamValueZeroOrOne<true> }, { id?: ParamValueZeroOrOne<false> }>,
    'wiki-search': RouteRecordInfo<'wiki-search', '/wiki/search', Record<never, never>, Record<never, never>>,
  }
}
