/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/autops': RouteRecordInfo<'/autops', '/autops', Record<never, never>, Record<never, never>>,
    'knowledge': RouteRecordInfo<'knowledge', '/knowledge', Record<never, never>, Record<never, never>>,
    'knowledge-article': RouteRecordInfo<'knowledge-article', '/knowledge/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'knowledge-create': RouteRecordInfo<'knowledge-create', '/knowledge/create', Record<never, never>, Record<never, never>>,
    'knowledge-list': RouteRecordInfo<'knowledge-list', '/knowledge/list', Record<never, never>, Record<never, never>>,
    'knowledge-search': RouteRecordInfo<'knowledge-search', '/knowledge/search', Record<never, never>, Record<never, never>>,
    'knowledge-article': RouteRecordInfo<'knowledge-article', '/knowledge/article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'knowledge-edit': RouteRecordInfo<'knowledge-edit', '/knowledge/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'knowledge-simple': RouteRecordInfo<'knowledge-simple', '/knowledge-simple', Record<never, never>, Record<never, never>>,
    'knowledge-test': RouteRecordInfo<'knowledge-test', '/knowledge-test', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/todos': RouteRecordInfo<'/todos', '/todos', Record<never, never>, Record<never, never>>,
  }
}
